apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: symfony-app

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  hostPath:
    path: /mnt/data
