apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: php
    spec:
      containers:
        - image: php
          name: symfony-app-php
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/symfony_app
              name: php-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: php-cm0
          name: php-cm0
